namespace YSMParser.Core.Crypto;

/// <summary>
/// High-level crypto operations used by YSM parser V3: XChaCha20 with dynamic
/// rounds, MT19937 XOR obfuscation, and Zstd decompression.
/// </summary>
public static class YsmCrypto
{
    /// <summary>Seed used for MT19937 key derivation.</summary>
    public const ulong SEED_KEY_DERIVATION = 0xD017CBBA7B5D3581UL;
    /// <summary>Seed used for resource verification hashing.</summary>
    public const ulong SEED_RES_VERIFICATION = 0xA62B1A2C43842BC3UL;
    /// <summary>Seed used for cache decryption.</summary>
    public const ulong SEED_CACHE_DECRYPTION = 0xD1C3D1D13A99752BUL;
    /// <summary>Seed used for file verification hashing.</summary>
    public const ulong SEED_FILE_VERIFICATION = 0x9E5599DB80C67C29UL;
    /// <summary>Seed used for packet verification hashing.</summary>
    public const ulong SEED_PACKET_VERIFICATION = 0xEE6FA63D570BD77BUL;
    /// <summary>Seed used for cache verification hashing.</summary>
    public const ulong SEED_CACHE_VERIFICATION = 0xF346451E53A22261UL;

    /// <summary>
    /// Updates the XChaCha20 state with dynamic round count based on a hash value.
    /// Mirrors <c>CryptoAlgorithms::xchacha_update_state</c>.
    /// </summary>
    /// <param name="ctx">The XChaCha20 context to update.</param>
    /// <param name="hashV">The hash value used to derive round count and XOR values.</param>
    /// <returns>The next block size in bytes, computed from the lower bits of the hash.</returns>
    public static uint XChaChaUpdateState(XChaChaCtx ctx, ulong hashV)
    {
        ctx.Rounds = 10 * (uint)(hashV % 3) + 10;

        uint lo = (uint)(hashV & 0xFFFFFFFFUL);
        uint hi = (uint)((hashV >> 32) & 0xFFFFFFFFUL);

        for (int i = 4; i < 16; ++i)
        {
            if (i % 2 == 0)
            {
                ctx.Input[i] ^= lo;
            }
            else
            {
                ctx.Input[i] ^= hi;
            }
        }

        return (uint)(((hashV & 0x3FUL) | 0x40UL) << 6);
    }

    /// <summary>
    /// Decrypts data using XChaCha20 with YSM-modified dynamic round counts.
    /// The round count and state are re-derived from hash values at each block boundary.
    /// </summary>
    /// <param name="data">The encrypted data.</param>
    /// <param name="key">The 32-byte encryption key.</param>
    /// <param name="iv">The 24-byte initialization vector.</param>
    /// <param name="seed">The seed used for hash-based state updates.</param>
    /// <returns>The decrypted data.</returns>
    public static byte[] ModifiedChaChaDecrypt(ReadOnlySpan<byte> data, ReadOnlySpan<byte> key, ReadOnlySpan<byte> iv, ulong seed)
    {
        Span<byte> keyIv = stackalloc byte[56];
        key.CopyTo(keyIv);
        iv.CopyTo(keyIv[32..]);

        ulong hash2 = CityHash64.CityHash64WithSeed(keyIv, 56, seed);
        uint nextRoundSize = (uint)(((hash2 & 0x3FUL) | 0x40UL) << 6);
        int blockPointer = 0;

        XChaChaCtx ctx = new()
        {
            Rounds = 10 * (uint)(hash2 % 3) + 10
        };
        XChaCha20.KeySetup(ctx, key, iv);

        byte[] result = GC.AllocateUninitializedArray<byte>(data.Length);

        while (blockPointer < data.Length)
        {
            if (blockPointer + nextRoundSize > data.Length)
            {
                nextRoundSize = (uint)(data.Length - blockPointer);
            }

            int remaining = (int)nextRoundSize;
            ReadOnlySpan<byte> encSpan = data.Slice(blockPointer, remaining);
            Span<byte> decSpan = result.AsSpan(blockPointer, remaining);

            // XChaCha20 internally processes 64-byte blocks with a running counter;
            // calling it with a multi-block span produces the same output as the
            // C++ xchacha_decrypt_bytes(...) call.
            XChaCha20.DecryptBytes(ctx, encSpan, decSpan, nextRoundSize);

            ulong resHash = CityHash64.CityHash64WithSeed(decSpan, remaining, seed);
            nextRoundSize = XChaChaUpdateState(ctx, resHash);

            blockPointer += remaining;
        }

        return result;
    }

    /// <summary>
    /// Decrypts data by XORing with a keystream generated by a seeded MT19937 PRNG.
    /// The seed is derived from the key and IV via <see cref="CityHash64"/>.
    /// </summary>
    /// <param name="data">The data to XOR-decrypt.</param>
    /// <param name="key">The 32-byte encryption key.</param>
    /// <param name="iv">The 24-byte initialization vector.</param>
    /// <returns>The decrypted data.</returns>
    public static byte[] MT19937XorDecrypt(ReadOnlySpan<byte> data, ReadOnlySpan<byte> key, ReadOnlySpan<byte> iv)
    {
        Span<byte> keyIv = stackalloc byte[56];
        key.CopyTo(keyIv);
        iv.CopyTo(keyIv[32..]);

        ulong seed = CityHash64.CityHash64WithSeed(keyIv, 56, SEED_KEY_DERIVATION);
        var mt = new Mt19937(seed);
        byte[] result = GC.AllocateUninitializedArray<byte>(data.Length);

        unsafe
        {
            fixed (byte* pData = data)
            fixed (byte* pResult = result)
            {
                ulong* pDataU = (ulong*)pData;
                ulong* pResultU = (ulong*)pResult;
                int nBlocks = data.Length / 8;
                for (int bi = 0; bi < nBlocks; bi++)
                {
                    pResultU[bi] = pDataU[bi] ^ mt.NextUInt64();
                }
                int tailStart = nBlocks * 8;
                if (tailStart < data.Length)
                {
                    ulong rnd = mt.NextUInt64();
                    byte* pTailData = pData + tailStart;
                    byte* pTailResult = pResult + tailStart;
                    for (int j = 0; tailStart + j < data.Length; j++)
                    {
                        pTailResult[j] = (byte)(pTailData[j] ^ (byte)((rnd >> (j * 8)) & 0xFF));
                    }
                }
            }
        }
        return result;
    }

    /// <summary>
    /// Decompresses YSM-wrapped Zstd data. Applies <see cref="YsmZstd.Wash"/> to
    /// undo the obfuscation before feeding the result into a standard Zstd decoder.
    /// </summary>
    /// <param name="compressedData">The YSM-obfuscated Zstd compressed data.</param>
    /// <returns>The decompressed data.</returns>
    /// <exception cref="InvalidOperationException">
    /// Thrown if decompression fails after multiple attempts with increasing buffer sizes.
    /// </exception>
    public static byte[] DecompressZstd(ReadOnlySpan<byte> compressedData)
    {
        byte[] washed = YsmZstd.Wash(compressedData);
        using var decompressor = new ZstdSharp.Decompressor();

        ulong exactSize = ZstdSharp.Decompressor.GetDecompressedSize(washed);
        if (exactSize > 0)
        {
            byte[] output = GC.AllocateUninitializedArray<byte>((int)exactSize);
            int written = decompressor.Unwrap(washed, output);
            if (written > 0)
            {
                return output;
            }
            throw new InvalidOperationException("Zstd decompression failed (no output produced).");
        }

        int maxSize = Math.Max(8, washed.Length * 4);
        for (int attempt = 0; attempt < 4; attempt++)
        {
            byte[] output = GC.AllocateUninitializedArray<byte>(maxSize);
            try
            {
                int written = decompressor.Unwrap(washed, output);
                if (written > 0)
                {
                    Array.Resize(ref output, written);
                    return output;
                }
            }
            catch (ZstdSharp.ZstdException)
            {
                // Buffer too small — retry with larger size.
            }
            maxSize *= 4;
        }
        throw new InvalidOperationException("Zstd decompression failed (no output produced).");
    }
}
